In [4]:
import numpy as np

In [7]:
random_int_array = np.random.randint(1, 100, size=(20))
random_int_array

array([20, 99, 17, 33, 57, 65, 31, 23, 90, 78, 26, 43, 51,  2, 86, 75, 87,
       77, 82, 37], dtype=int32)

In [9]:

condition = random_int_array > 50
filtered_arr = rando
m_int_array[condition]
filtered_arr

array([99, 57, 65, 90, 78, 51, 86, 75, 87, 77, 82], dtype=int32)

In [8]:
arr1 = np.random.randint(1, 100, size=(3))
arr2 = np.random.randint(1, 100, size=(3))
arr2

array([46, 24, 17], dtype=int32)

In [9]:
arr1

array([79, 14, 83], dtype=int32)

In [11]:
ab = arr1 + arr2
ab

array([125,  38, 100], dtype=int32)

In [15]:
average = np.mean(ab)
average

np.float64(87.66666666666667)